apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: innloggingsstatus
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /person/innloggingsstatus/internal/isAlive
    initialDelay: 5
  readiness:
    path: /person/innloggingsstatus/internal/isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /person/innloggingsstatus/internal/metrics
  replicas:
    min: 2
    max: 4
  idporten:
    enabled: true
  webproxy: true
  ingresses:
  {{#each ingresses}}
    - "{{this}}"
  {{/each}}
  vault:
    enabled: true
    paths:
      - kvPath: /kv/{{vault_secrets_root}}/sbs/innloggingsstatus/personbruker
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /serviceuser/data/{{vault_namespace}}/srvinnloggstatus
        mountPath: /secret/serviceuser
      - kvPath: /apikey/apigw/{{vault_namespace}}/pdl-api/{{vault_consumer_name}}
        mountPath: /secret/pdl_apiKey
      - kvPath: /apikey/apigw/{{vault_namespace}}/security-token-service-token/{{vault_consumer_name}}
        mountPath: /secret/sts_apiKey
  envFrom:
    - configmap: loginservice-idporten
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 384Mi

